CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS channels (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 handle VARCHAR(120) NOT NULL,
 destination VARCHAR(120) NOT NULL DEFAULT '',
 preset VARCHAR(30) NOT NULL DEFAULT 'vivid',
 auto_publish TINYINT NOT NULL DEFAULT 0,
 enabled TINYINT NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY source_destination(handle,destination)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS schedules (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 channel_id BIGINT UNSIGNED NOT NULL UNIQUE,
 interval_minutes INT UNSIGNED NOT NULL DEFAULT 60,
 enabled TINYINT NOT NULL DEFAULT 1,
 next_run DATETIME NOT NULL,
 last_run DATETIME NULL,
 FOREIGN KEY(channel_id) REFERENCES channels(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS jobs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 channel_id BIGINT UNSIGNED NOT NULL,
 status VARCHAR(32) NOT NULL DEFAULT 'queued',
 stage VARCHAR(32) NOT NULL DEFAULT 'discover',
 progress SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 source_video_id VARCHAR(32) NULL,
 source_url VARCHAR(500) NULL,
 original_title VARCHAR(255) NULL,
 title VARCHAR(255) NULL,
 published_url VARCHAR(500) NULL,
 error TEXT NULL,
 attempts INT UNSIGNED NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 finished_at DATETIME NULL,
 FOREIGN KEY(channel_id) REFERENCES channels(id),
 INDEX status_created(status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 job_id BIGINT UNSIGNED NULL,
 source VARCHAR(40) NOT NULL,
 level VARCHAR(20) NOT NULL DEFAULT 'info',
 message TEXT NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX job_cursor(job_id,id),
 INDEX event_time(created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS workers (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL UNIQUE,
 kind VARCHAR(30) NOT NULL,
 version VARCHAR(30) NOT NULL DEFAULT '',
 last_seen DATETIME NULL,
 current_job BIGINT UNSIGNED NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS login_attempts (
 address_hash CHAR(64) PRIMARY KEY,
 attempts INT UNSIGNED NOT NULL DEFAULT 0,
 window_start DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
