<?php
declare(strict_types=1);
require __DIR__.'/private/core.php';
header('Cache-Control: no-store'); header('X-Frame-Options: DENY');
header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");
if(!configuration()){header('Location: setup.php');exit;}
session_open();
$isAdmin=!empty($_SESSION['user_id']) && ($_SESSION['last_seen']??0)>=time()-28800;
if($isAdmin) $_SESSION['last_seen']=time();
$csrf=$_SESSION['csrf']; $email=$isAdmin?$_SESSION['email']:'';session_write_close();
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="<?=h($csrf)?>"><meta name="access-mode" content="<?=$isAdmin?'admin':'public'?>"><meta name="robots" content="noindex,nofollow"><title>Astra Video · Control room</title><link rel="stylesheet" href="assets/app.css?v=0.1.1"><link rel="stylesheet" href="assets/dark.css?v=1"><link rel="stylesheet" href="assets/operations.css?v=2"><link rel="stylesheet" href="assets/workspace.css?v=1"><script defer src="assets/operations.js?v=4"></script><script defer src="assets/app.js?v=3"></script></head>
<body><aside class="sidebar"><a class="brand" href="#overview"><span class="brand-mark">a</span> astra<span class="brand-sub">VIDEO</span></a><div class="workspace"><span class="workspace-avatar">AV</span><div>Astra workspace<small>Video operations</small></div><span class="chevron">⌄</span></div><p class="nav-label">WORKSPACE</p><nav aria-label="Main navigation"><a href="#overview" data-page="overview"><span>◫</span> Control room</a><a href="#jobs" data-page="jobs"><span>≡</span> Queue <b id="nav-queue">0</b></a><a href="#library" data-page="library"><span>▤</span> Video library</a><a href="#channels" data-page="channels"><span>◎</span> Channels</a><a href="#schedules" data-page="schedules"><span>◷</span> Scheduler</a><a href="#errors" data-page="errors"><span>⚠</span> Errors <b id="nav-errors">0</b></a><a href="#console" data-page="console"><span>›_</span> Live console</a><a href="#analytics" data-page="analytics"><span>▥</span> Analytics</a></nav><div class="sidebar-bottom"><div class="worker-card"><span class="status-dot amber"></span><strong>Checking VPS status</strong><small>Open Control room for live agent status.</small></div><a href="#settings" data-page="settings" class="settings-link">⚙ <span>Settings</span></a><?php if($isAdmin): ?><button id="logout" class="profile"><span class="profile-avatar">A</span><span>Administrator<small><?=h($email)?></small></span><span>↗</span></button><?php else: ?><div class="profile"><span class="profile-avatar">◉</span><span>Public dashboard<small>Read-only access</small></span></div><?php endif; ?></div></aside>
<button id="sidebar-scrim" class="sidebar-scrim" aria-label="Close navigation" hidden></button><div class="main-shell"><header class="topbar"><button id="menu-toggle" class="icon-button mobile-only" aria-label="Toggle navigation" aria-expanded="false">☰</button><div class="breadcrumb">Workspace <span>/</span> <strong id="crumb">Overview</strong></div><div class="topbar-right"><span class="pill" id="connection-pill"><span class="status-dot"></span> Connecting</span><span class="timezone">SL · UTC+05:30</span><?php if(!$isAdmin): ?><a href="login.php" class="pill readonly-pill">Read only · Manage ↗</a><?php endif; ?><button id="refresh" class="icon-button" aria-label="Refresh dashboard">↻</button></div></header><main id="main"><div class="page-heading"><div><p class="eyebrow">YOUR CONTENT, IN MOTION</p><h1 id="page-title">Overview</h1><p id="page-description" class="muted">Everything happening across your video pipeline.</p></div><button id="primary-action" class="button primary" <?=$isAdmin?'':'hidden'?>>＋ New job</button></div><div id="notice" class="notice" hidden><span class="notice-icon">i</span><div><strong>Schedule ready. Waiting for VPS agents.</strong><p>Controls save real queue state. Countdown clocks show planned slots; execution begins when the VPS runner and Chrome extension connect.</p></div><a href="#settings">View setup →</a></div><div id="page-content" aria-live="polite"><div class="loading">Loading your workspace…</div></div><footer class="footer"><span>ASTRA VIDEO <b>v0.2 · Agent control room</b></span><span id="last-sync">Connecting to workspace</span></footer></main></div>
<dialog id="modal"><div class="modal-heading"><div><p class="eyebrow">WORKSPACE</p><h2 id="modal-title">New job</h2></div><button class="icon-button" id="modal-close" aria-label="Close dialog">×</button></div><form id="modal-form"><div id="modal-fields"></div><p id="modal-error" class="error" hidden></p><div class="modal-actions"><button type="button" id="modal-cancel" class="button">Cancel</button><button type="submit" id="modal-submit" class="button primary">Save</button></div></form></dialog><div id="toast" role="status" hidden></div>
</body></html>
